name: Cypress Tests
# Устанавливаем триггер
on: [push]
jobs:
  cypress-run:
# Развертываем среду Widows c Cypress 
    runs-on: windows-latest
    steps:
# Копируем в эту среду наш репазиторий
      - name: Checkout
        uses: actions/checkout@v3
# Запускаем тест. Будет искать в ./e2e. Сколько найдет, столько выполнит. 
      - name: Cypress run 
        uses: cypress-io/github-action@v5
# Хотим Chrome
        with:
          browser: chrome
# Хотим скрины
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
# Хотим видео
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          